name: Build Android (Flutter)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # دکمه‌ی "Run workflow" را فعال می‌کند

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # جاوا 17 برای AGP 8.x
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      # ستاپ فلاتر (ورژن را در صورت نیاز تغییر بده)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.3'
          cache: true

      # بیلد تمیز
      - name: Clean caches
        run: |
          flutter clean
          rm -rf ~/.gradle/caches || true

      - name: Get Flutter dependencies
        run: flutter pub get

      # ساختن android/local.properties تا خطای "Flutter source directory" نگیری
      - name: Generate android/local.properties
        run: |
          ANDROID_SDK_ROOT="$HOME/Android/Sdk"
          mkdir -p "$ANDROID_SDK_ROOT"
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
          echo "flutter.sdk=$FLUTTER_HOME" >> android/local.properties
        env:
          FLUTTER_HOME: ${{ env.FLUTTER_HOME }}

      # اطلاعات محیط برای دیباگ
      - name: Environment info
        run: |
          flutter --version
          java -version
          echo "JAVA_HOME=$JAVA_HOME"

      # ---- اگر دو ورودی جدا داری، یکی را انتخاب کن. این یکی Seller است:
      - name: Build Seller APK (debug)
        run: flutter build apk --debug --target=lib/seller_main.dart --split-per-abi

      # اگر Buyer هم می‌خوای، این استپ را هم فعال کن:
      # - name: Build Buyer APK (debug)
      #   run: flutter build apk --debug --target=lib/buyer_main.dart --split-per-abi

      # آپلود خروجی‌ها
      - name: Upload APKs
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: build/app/outputs/flutter-apk/*.apk
